CREATE TABLE [User]
(
	ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID() NOT NULL,
	ACCOUNT_ID UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
	EMAIL VARCHAR(500) NOT NULL,
	[PASSWORD] VARCHAR (500) NOT NULL
);

CREATE TABLE Scope(
	ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID() NOT NULL,
	[NAME] VARCHAR(500) NOT NULL,
	[DESCRIPTION] VARCHAR(500) NOT NULL
);

CREATE TABLE ScopeUser(
	ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID() NOT NULL,
	[USER_ID] UNIQUEIDENTIFIER NOT NULL,
	[SCOPE_ID] UNIQUEIDENTIFIER NOT NULL,

	CONSTRAINT FK_ScopeUser_User FOREIGN KEY ([USER_ID]) 
		REFERENCES [User](ID),
	CONSTRAINT FK_ScopeUser_Scope FOREIGN KEY ([SCOPE_ID]) 
		REFERENCES [Scope](ID),
);

CREATE TABLE Rules(
	ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID() NOT NULL,
	[NAME] VARCHAR(500) NOT NULL,
	[DESCRIPTION] VARCHAR(500) NOT NULL,
	[SCOPE_ID] UNIQUEIDENTIFIER NOT NULL,

	CONSTRAINT FK_RULES_SCOPE FOREIGN KEY ([SCOPE_ID])
		REFERENCES SCOPE(ID)
);


CREATE TABLE RulesUser(
	ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID() NOT NULL,
	[USER_ID] UNIQUEIDENTIFIER NOT NULL,
	RULES_ID UNIQUEIDENTIFIER NOT NULL,

	CONSTRAINT FK_RulesUser_User FOREIGN KEY ([USER_ID]) 
		REFERENCES [User](ID),
	CONSTRAINT FK_RulesUser_Rules FOREIGN KEY (RULES_ID) 
		REFERENCES Rules (ID),

);


ALTER TABLE [User]
ADD CREATED_AT DATETIME NOT NULL DEFAULT GETDATE(),
CREATED_BY VARCHAR(500) NOT NULL,
UPDATED_AT DATETIME NULL,
UPDATED_BY VARCHAR (500) NULL;


ALTER TABLE Scope
ADD CREATED_AT DATETIME NOT NULL DEFAULT GETDATE(),
CREATED_BY VARCHAR(500) NOT NULL,
UPDATED_AT DATETIME NULL,
UPDATED_BY VARCHAR (500) NULL;


ALTER TABLE Rules
ADD CREATED_AT DATETIME NOT NULL DEFAULT GETDATE(),
CREATED_BY VARCHAR(500) NOT NULL,
UPDATED_AT DATETIME NULL,
UPDATED_BY VARCHAR (500) NULL;


