CREATE TABLE [User]
(
	ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID() NOT NULL,
	ACCOUNT_ID UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
	EMAIL VARCHAR(500) NOT NULL,
	[PASSWORD] VARCHAR (500) NOT NULL
);

CREATE TABLE Scope(
	ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID() NOT NULL,
	[NAME] VARCHAR(500),
	[DESCRIPTION] VARCHAR(500)
);